# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Synapse Matrix homeserver
version: "0.6.0-beta5"
slug: synapse
description: Homeserver for Matrix (A secure and decentralized communication platform).
url: "https://github.com/delsonlima/hassio-addons/tree/main/synapse"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
map:
  - "addon_config:rw"
  - "homeassistant_config:rw"
  - "ssl:rw"
options:
  data_dir: /config
  server_name:
  report_stats: false
ports:
  8008/tcp: 8008
ports_description:
  8008/tcp: Synapse default port
schema:
  data_dir: str
  server_name: str
  TZ: str?
  report_stats: bool
# image: "ghcr.io/delsonlima/hassio-addons/synapse-{arch}"
